### PR TITLE
Fix returning value of method writers. Fix value of begin-rescue-else-ensure-end

### LINKED ISSUE #1518: Opal Master Return with a begin...else is broken
I'll try and work on a PR:

Note that in the `finally/$no_errors if`, the true used to have a return statement and now it doesn't.

Ruby:
```ruby
def match_unless_raises(expected_exception=Exception, &match_block)
  define_user_override(:matches?, match_block) do |actual|
    @actual = actual
    begin
      super(*actual_arg_for(match_block))
    rescue expected_exception => @rescued_exception
      false
    else
      true
    end
  end
end
```

Compiled with `opal -c --no-opal -A`

Opal 0.10:
```js
/* Generated by Opal 0.10.1 */
(function(Opal) {
  var TMP_1, self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$define_user_override', '$actual_arg_for']);
  return (Opal.defn(Opal.Object, '$match_unless_raises', TMP_1 = function ːmatch_unless_raises(expected_exception) {
    var $a, $b, TMP_2, self = this, $iter = TMP_1.$$p, match_block = $iter || nil;

    if (expected_exception == null) {
      expected_exception = $scope.get('Exception');
    }
    TMP_1.$$p = null;
    var $arity = arguments.length; if ($arity > 1) { Opal.ac($arity, -1, this, "match_unless_raises"); }
    return ($a = ($b = self).$define_user_override, $a.$$p = (TMP_2 = function(actual){var self = TMP_2.$$s || this, $c, $d;
if (actual == null) actual = nil;
      if (TMP_2.$$is_lambda || TMP_2.$$define_meth) {
        var $arity = arguments.length;
        if ($arity !== 1) { Opal.block_ac($arity, 1, 'match_unless_raises'); }
      }
    self.actual = actual;
      
      var $no_errors = true;try {
        return ($c = ($d = self, Opal.find_iter_super_dispatcher(self, 'match_unless_raises', (TMP_2.$$def || TMP_1), false, false)), $c.$$p = null, $c).apply($d, Opal.to_a(self.$actual_arg_for(match_block)))
      } catch ($err) {
        $no_errors = false;
        if (Opal.rescue($err, [expected_exception])) {self.rescued_exception = $err;
          try {
            return false
          } finally { Opal.pop_exception() }
        } else { throw $err; }
      }finally {
        if ($no_errors) { 
          return (function() {
            return true
          })();
        }};}, TMP_2.$$s = self, TMP_2.$$arity = 1, TMP_2.$$parameters = [['req', 'actual']], TMP_2), $a).call($b, "matches?", match_block);
  }, TMP_1.$$arity = -1, TMP_1.$$parameters = [['opt', 'expected_exception'], ['block', 'match_block']]), nil) && 'match_unless_raises'
})(Opal);

/* Generated by Opal 0.10.1 */
(function(Opal) {
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$exit']);
  return $scope.get('Kernel').$exit()
})(Opal);
```

Opal master:
```js
>> BUNDLE_GEMFILE=/host/gemfiles/opal_master.gemfile bundle exec opal -c --no-opal -A foo.rb
/* Generated by Opal 0.11.0.dev */
(function(Opal) {
  var TMP_1, self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$define_user_override', '$actual_arg_for']);
  return (Opal.defn(Opal.Object, '$match_unless_raises', TMP_1 = function ːmatch_unless_raises(expected_exception) {
    var $a, $b, TMP_2, self = this, $iter = TMP_1.$$p, match_block = $iter || nil;

    if (expected_exception == null) {
      expected_exception = $scope.get('Exception');
    }
    TMP_1.$$p = null;
    var $arity = arguments.length; if ($arity > 1) { Opal.ac($arity, -1, this, "match_unless_raises"); }
    return ($a = ($b = self).$define_user_override, $a.$$p = (TMP_2 = function(actual){var self = TMP_2.$$s || this, $c, $d;
if (actual == null) actual = nil;
      if (TMP_2.$$is_lambda || TMP_2.$$define_meth) {
        var $arity = arguments.length;
        if ($arity !== 1) { Opal.block_ac($arity, 1, 'match_unless_raises'); }
      }
    
      self.actual = actual;
      
      
      var $no_errors = true;try {
        return ($c = ($d = self, Opal.find_iter_super_dispatcher(self, 'match_unless_raises', (TMP_2.$$def || TMP_1), false, false)), $c.$$p = null, $c).apply($d, Opal.to_a(self.$actual_arg_for(match_block)))
      } catch ($err) {
        $no_errors = false;
        if (Opal.rescue($err, [expected_exception])) {self.rescued_exception = $err;
          try {
            return false
          } finally { Opal.pop_exception() }
        } else { throw $err; }
      }finally {
        if ($no_errors) { 
          true
        }};;}, TMP_2.$$s = self, TMP_2.$$arity = 1, TMP_2.$$parameters = [['req', 'actual']], TMP_2), $a).call($b, "matches?", match_block)
  }, TMP_1.$$arity = -1, TMP_1.$$parameters = [['opt', 'expected_exception'], ['block', 'match_block']]), nil) && 'match_unless_raises'
})(Opal);

/* Generated by Opal 0.11.0.dev */
(function(Opal) {
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$exit']);
  return $scope.get('Kernel').$exit()
})(Opal);

```

### LINKED ISSUE #1520: Setter Return Value
Should ignore the return value from the method, worked OK in Opal 0.10.1. Seems to not happen if it's a standalone method, had to put it in a class.

```ruby
class Foo
  def foobar=(*)
    1
  end
end

puts (Foo.new.foobar = 'bar')
```

Just ran with `opal foo.rb`

MRI output: `bar`
0.10.1 output: `bar`
Opal master output: `1`

### PR DESCRIPTION
**Pull request by iliabylich**
Partially closes #1520
Completely closes #1518

### CODE REVIEW

File: lib/opal/rewriter.rb [hunk 1]
```diff
@@ -1,9 +1,11 @@
 require 'opal/rewriters/opal_engine_check'
+require 'opal/rewriters/explicit_writer_return'
 
 module Opal
   class Rewriter
     LIST = [
-      Rewriters::OpalEngineCheck
+      Rewriters::OpalEngineCheck,
+      Rewriters::ExplicitWriterReturn,
```
Comment (elia) [inline lib/opal/rewriter.rb]: 👍🏼 on the trailing comma :)

**Comment by catmando** [comment]
does this fix this:

def foo

rescue

ensure

x
end

x is not returned unless you say return x ???

**Comment by iliabylich** [comment]
@catmando Yes, this is how MRI works:
``` ruby
def foo(x)
rescue
ensure
  x
end

p foo(1)

def foo_with_explicit_return(x)
rescue
ensure
  return x
end

p foo_with_explicit_return(1)
```

```
$ ruby test.rb
nil
1
```

```
$ opal test.rb
nil
1
```

You shouldn't use `ensure` to generate returning value. MRI returns only `begin/else/rescue` nodes:

``` ruby
def foo(&block)
  block.call
rescue
  'rescue'
ensure
  'ensure'
end

p foo { 1 }
p foo { raise 'error' }

def foo_with_else(&block)
  block.call
rescue
  'rescue'
else
  'else'
ensure
  'ensure'
end

p foo_with_else { 1 }
p foo_with_else { raise 'error' }
```

```
$ ruby test.rb
1
"rescue"
"else"
"rescue"
```

```
opal test.rb
1
"rescue"
"else"
"rescue"
```
