### PR TITLE
Super/Aliasing Fix

### LINKED ISSUE #1384: Super/Alias Problem
Weird edge case. I might be able to fix this soon but wanted to document it. Has something to do with alias_method & super

code:
```ruby
module Mod
  attr_reader :foobar
end

class Foo
  include Mod
    
  def initialize
    @foobar = :yes
  end
    
  def foobar
    super()
  end

  alias_method "foobar?", :foobar
    
  def foobar
    @foobar
  end
end

puts 'call regular'
puts Foo.new.foobar
puts 'call alias'
puts Foo.new.foobar?
```

ran `ruby test.rb`:
```
call regular
yes
call alias
yes
```

ran `bundle exec opal -A test.rb`:
```
call regular
yes
call alias

/tmp/opal-nodejs-runner-20160306-1265-182v9i:1073
      throw new Error("could not find current class for super()");
            ^
Error: could not find current class for super()
    at Opal.find_obj_super_dispatcher (/tmp/opal-nodejs-runner-20160306-1265-182v9i:1073:13)
    at Opal.find_super_dispatcher (/tmp/opal-nodejs-runner-20160306-1265-182v9i:1025:27)
    at Opal.find_iter_super_dispatcher (/tmp/opal-nodejs-runner-20160306-1265-182v9i:1055:17)
    at $Foo.$a.$$p.TMP_2 [as $foobar?] (/tmp/opal-nodejs-runner-20160306-1265-182v9i:19891:37)
    at Opal.dynamic_require_severity (/tmp/opal-nodejs-runner-20160306-1265-182v9i:19907:57)
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20160306-1265-182v9i:19908:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

### PR DESCRIPTION
**Pull request by wied03**
Fixes #1384. Another weird quirk of the Ruby language (if it's a weird corner, RSpec will find it). It still needs the following:
- Rubyspec built from the anon_mod.rb file *done*
- This is probably incomplete as it really needs to be something that also fixes the Rubyspec `Module#alias_method can call a method with super aliased twice` *save this for another PR*

### CODE REVIEW

**Comment by wied03** [comment]
@meh - any thoughts here?

File: opal/corelib/runtime.js [hunk 1]
```diff
@@ -1347,6 +1356,8 @@
   //
   Opal.defn = function(obj, jsid, body) {
     obj.$$proto[jsid] = body;
+    // super dispatcher find, etc. might need to lookup by function body
+    obj.$$funcbodies[body] = jsid;
```
Comment (elia) [inline opal/corelib/runtime.js]: This rings an alarm for me, `[body]` will convert the function to a string and use that as the key, which means that will use the actual source code of the function to identify it. That, to me, is a problem because:

- two methods in the inheritance chain can have the same implementation this defeating this technique (even if I'm aware it's surely not common)
- I'm not sure how standard is to have `Function.prototype.toString()` converto the function to its source code, what if the implementation is changed?
- looks like a hack
- could mislead a future me reading this code

Even if I recognize it's practical, I'd rather prefer to have a more robust system, that actually checks a prototype chain for the particular method or alternatively assign an `Opal.uid()` to each function and use that instead of the function body.

Comment (wied03) [inline opal/corelib/runtime.js]: What about the first way/first commit?

sent from my mobile device

**Comment by wied03** [comment]
rubyspecs - https://github.com/ruby/spec/pull/212

**Comment by wied03** [comment]
@elia - Thanks for the earlier feedback. I think with this 2nd commit, I got the nested loop eliminated and have something that can work OK.

**Comment by elia** [comment]
:+1: :)
